@cookie = "auth-cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODUsImlhdCI6MTY2MzUxMjEwNX0.VbuJtbuCa2ozPFYz60xtsM5tVnNN2ggxXSvN9sWDf3g; Path=/; Expires=Tue, 18 Oct 2022 14:41:45 GMT"
@article_id = 9
@id = 50
####
POST http://localhost:4000/api/articles
Cookie: {{cookie}}
Content-Type: application/json

{
        "title": "Bonjour monsieur LE MOCHE",
        "img": "img.PNG",
        "resume_article": "resume",
        "content_article": "",
        "author_article": "Maryse",
        "video": "kkkkk",
        "admin_id": 2
}

###
GET http://localhost:4000/api/articles
Cookie: {{cookie}}

###
GET http://localhost:4000/api/derniersArticles

###
GET http://localhost:4000/api/allArticles

###
GET http://localhost:4000/api/adminArticleDetails/{{article_id}}
Cookie: {{cookie}}

###
GET http://localhost:4000/api/visitorArticle/{{id}}

###
DELETE http://localhost:4000/api/article/{{id}}
Cookie: {{cookie}}

###
PUT http://localhost:4000/api/article/{{id}}
Cookie: {{cookie}}
Content-Type: application/json

{
        "title": "Bonjour monsieur LE MOCHE",
        "img": "/",
        "resume_article": "resume",
        "content_article": "ee",
        "author_article": "Maryse",
        "video": "kkkkk"
      
}
