POST http://localhost:4000/api/adminRegister/
Content-Type: application/json
{

   "user_name": "Amélia",
   "email": "kldlsdddddllfnxxkjk@dkkgmail.com",
   "password": "ddddddM0dMd"

}
####
POST http://localhost:4000/api/adminlogin
Content-Type: application/json

{
   "user_name": "Amoulou",
   "email": "ameliakanu@jmail.com",
   "password": "kkkA.100000"
}